/**
 * Mapping des champs Manuels-Didactics (Manuels-Didactics, codes 5100-5133).
 * Categorie C integrale : aucune source dans ZekoulABia (pas de module bibliotheque).
 * Admin remplit via formulaire complementaire (manuelsDetail Json dans SchoolStatisticalSupplement).
 *
 * Structure V.1 (nombre de livres) :
 *   Colonnes D-H = Form1-Form5 (1er cycle EN), I-J = Lower/Upper 6th (2nd cycle EN)
 *   K = Other, L = Total (FORMULE)
 *   M-P = 6e-3e (1er cycle FR), Q-S = 2nde-Tle (2nd cycle FR)
 *
 * Codes 5100-5132 = une ligne par discipline
 * Code 5133 = Total (FORMULE)
 */

export interface ManuelsFieldEntry {
  fieldCode: string;
  discipline: string;
  anglophoneCells: { level: string; cell: string }[];
  francophoneCells: { level: string; cell: string }[];
  otherCell: string;
}

export const MANUELS_FIELD_MAPPING: ManuelsFieldEntry[] = [
  { fieldCode: '5100', discipline: 'Francais/French', anglophoneCells: [{ level: 'Form1', cell: 'D16' }, { level: 'Form2', cell: 'E16' }, { level: 'Form3', cell: 'F16' }, { level: 'Form4', cell: 'G16' }, { level: 'Form5', cell: 'H16' }, { level: 'LowerSixth', cell: 'I16' }, { level: 'UpperSixth', cell: 'J16' }], francophoneCells: [{ level: '6e', cell: 'M16' }, { level: '5e', cell: 'N16' }, { level: '4e', cell: 'O16' }, { level: '3e', cell: 'P16' }, { level: '2nde', cell: 'Q16' }, { level: '1ere', cell: 'R16' }, { level: 'Tle', cell: 'S16' }], otherCell: 'K16' },
  { fieldCode: '5101', discipline: 'Anglais/English', anglophoneCells: [{ level: 'Form1', cell: 'D17' }, { level: 'Form2', cell: 'E17' }, { level: 'Form3', cell: 'F17' }, { level: 'Form4', cell: 'G17' }, { level: 'Form5', cell: 'H17' }, { level: 'LowerSixth', cell: 'I17' }, { level: 'UpperSixth', cell: 'J17' }], francophoneCells: [{ level: '6e', cell: 'M17' }, { level: '5e', cell: 'N17' }, { level: '4e', cell: 'O17' }, { level: '3e', cell: 'P17' }, { level: '2nde', cell: 'Q17' }, { level: '1ere', cell: 'R17' }, { level: 'Tle', cell: 'S17' }], otherCell: 'K17' },
  { fieldCode: '5102', discipline: 'Maths/Mathematics', anglophoneCells: [{ level: 'Form1', cell: 'D18' }, { level: 'Form2', cell: 'E18' }, { level: 'Form3', cell: 'F18' }, { level: 'Form4', cell: 'G18' }, { level: 'Form5', cell: 'H18' }, { level: 'LowerSixth', cell: 'I18' }, { level: 'UpperSixth', cell: 'J18' }], francophoneCells: [{ level: '6e', cell: 'M18' }, { level: '5e', cell: 'N18' }, { level: '4e', cell: 'O18' }, { level: '3e', cell: 'P18' }, { level: '2nde', cell: 'Q18' }, { level: '1ere', cell: 'R18' }, { level: 'Tle', cell: 'S18' }], otherCell: 'K18' },
  { fieldCode: '5103', discipline: 'Physiques/Physics', anglophoneCells: [{ level: 'Form1', cell: 'D19' }, { level: 'Form2', cell: 'E19' }, { level: 'Form3', cell: 'F19' }, { level: 'Form4', cell: 'G19' }, { level: 'Form5', cell: 'H19' }, { level: 'LowerSixth', cell: 'I19' }, { level: 'UpperSixth', cell: 'J19' }], francophoneCells: [{ level: '6e', cell: 'M19' }, { level: '5e', cell: 'N19' }, { level: '4e', cell: 'O19' }, { level: '3e', cell: 'P19' }, { level: '2nde', cell: 'Q19' }, { level: '1ere', cell: 'R19' }, { level: 'Tle', cell: 'S19' }], otherCell: 'K19' },
  { fieldCode: '5104', discipline: 'Chimie/Chemistry', anglophoneCells: [{ level: 'Form1', cell: 'D20' }, { level: 'Form2', cell: 'E20' }, { level: 'Form3', cell: 'F20' }, { level: 'Form4', cell: 'G20' }, { level: 'Form5', cell: 'H20' }, { level: 'LowerSixth', cell: 'I20' }, { level: 'UpperSixth', cell: 'J20' }], francophoneCells: [{ level: '6e', cell: 'M20' }, { level: '5e', cell: 'N20' }, { level: '4e', cell: 'O20' }, { level: '3e', cell: 'P20' }, { level: '2nde', cell: 'Q20' }, { level: '1ere', cell: 'R20' }, { level: 'Tle', cell: 'S20' }], otherCell: 'K20' },
  { fieldCode: '5105', discipline: 'Histoire/History', anglophoneCells: [{ level: 'Form1', cell: 'D21' }, { level: 'Form2', cell: 'E21' }, { level: 'Form3', cell: 'F21' }, { level: 'Form4', cell: 'G21' }, { level: 'Form5', cell: 'H21' }, { level: 'LowerSixth', cell: 'I21' }, { level: 'UpperSixth', cell: 'J21' }], francophoneCells: [{ level: '6e', cell: 'M21' }, { level: '5e', cell: 'N21' }, { level: '4e', cell: 'O21' }, { level: '3e', cell: 'P21' }, { level: '2nde', cell: 'Q21' }, { level: '1ere', cell: 'R21' }, { level: 'Tle', cell: 'S21' }], otherCell: 'K21' },
  { fieldCode: '5106', discipline: 'Geographie/Geography', anglophoneCells: [{ level: 'Form1', cell: 'D22' }, { level: 'Form2', cell: 'E22' }, { level: 'Form3', cell: 'F22' }, { level: 'Form4', cell: 'G22' }, { level: 'Form5', cell: 'H22' }, { level: 'LowerSixth', cell: 'I22' }, { level: 'UpperSixth', cell: 'J22' }], francophoneCells: [{ level: '6e', cell: 'M22' }, { level: '5e', cell: 'N22' }, { level: '4e', cell: 'O22' }, { level: '3e', cell: 'P22' }, { level: '2nde', cell: 'Q22' }, { level: '1ere', cell: 'R22' }, { level: 'Tle', cell: 'S22' }], otherCell: 'K22' },
  { fieldCode: '5107', discipline: 'ECM/ECM', anglophoneCells: [{ level: 'Form1', cell: 'D23' }, { level: 'Form2', cell: 'E23' }, { level: 'Form3', cell: 'F23' }, { level: 'Form4', cell: 'G23' }, { level: 'Form5', cell: 'H23' }, { level: 'LowerSixth', cell: 'I23' }, { level: 'UpperSixth', cell: 'J23' }], francophoneCells: [{ level: '6e', cell: 'M23' }, { level: '5e', cell: 'N23' }, { level: '4e', cell: 'O23' }, { level: '3e', cell: 'P23' }, { level: '2nde', cell: 'Q23' }, { level: '1ere', cell: 'R23' }, { level: 'Tle', cell: 'S23' }], otherCell: 'K23' },
  { fieldCode: '5108', discipline: 'Philosophie/Philosophy', anglophoneCells: [{ level: 'Form1', cell: 'D24' }, { level: 'Form2', cell: 'E24' }, { level: 'Form3', cell: 'F24' }, { level: 'Form4', cell: 'G24' }, { level: 'Form5', cell: 'H24' }, { level: 'LowerSixth', cell: 'I24' }, { level: 'UpperSixth', cell: 'J24' }], francophoneCells: [{ level: '6e', cell: 'M24' }, { level: '5e', cell: 'N24' }, { level: '4e', cell: 'O24' }, { level: '3e', cell: 'P24' }, { level: '2nde', cell: 'Q24' }, { level: '1ere', cell: 'R24' }, { level: 'Tle', cell: 'S24' }], otherCell: 'K24' },
  { fieldCode: '5109', discipline: 'Informatique/Computer studies', anglophoneCells: [{ level: 'Form1', cell: 'D25' }, { level: 'Form2', cell: 'E25' }, { level: 'Form3', cell: 'F25' }, { level: 'Form4', cell: 'G25' }, { level: 'Form5', cell: 'H25' }, { level: 'LowerSixth', cell: 'I25' }, { level: 'UpperSixth', cell: 'J25' }], francophoneCells: [{ level: '6e', cell: 'M25' }, { level: '5e', cell: 'N25' }, { level: '4e', cell: 'O25' }, { level: '3e', cell: 'P25' }, { level: '2nde', cell: 'Q25' }, { level: '1ere', cell: 'R25' }, { level: 'Tle', cell: 'S25' }], otherCell: 'K25' },
  { fieldCode: '5110', discipline: 'SVT/Biology', anglophoneCells: [{ level: 'Form1', cell: 'D26' }, { level: 'Form2', cell: 'E26' }, { level: 'Form3', cell: 'F26' }, { level: 'Form4', cell: 'G26' }, { level: 'Form5', cell: 'H26' }, { level: 'LowerSixth', cell: 'I26' }, { level: 'UpperSixth', cell: 'J26' }], francophoneCells: [{ level: '6e', cell: 'M26' }, { level: '5e', cell: 'N26' }, { level: '4e', cell: 'O26' }, { level: '3e', cell: 'P26' }, { level: '2nde', cell: 'Q26' }, { level: '1ere', cell: 'R26' }, { level: 'Tle', cell: 'S26' }], otherCell: 'K26' },
  { fieldCode: '5111', discipline: 'Technologie/PCT', anglophoneCells: [{ level: 'Form1', cell: 'D27' }, { level: 'Form2', cell: 'E27' }, { level: 'Form3', cell: 'F27' }, { level: 'Form4', cell: 'G27' }, { level: 'Form5', cell: 'H27' }, { level: 'LowerSixth', cell: 'I27' }, { level: 'UpperSixth', cell: 'J27' }], francophoneCells: [{ level: '6e', cell: 'M27' }, { level: '5e', cell: 'N27' }, { level: '4e', cell: 'O27' }, { level: '3e', cell: 'P27' }, { level: '2nde', cell: 'Q27' }, { level: '1ere', cell: 'R27' }, { level: 'Tle', cell: 'S27' }], otherCell: 'K27' },
  { fieldCode: '5112', discipline: 'Langue vivante II', anglophoneCells: [{ level: 'Form1', cell: 'D28' }, { level: 'Form2', cell: 'E28' }, { level: 'Form3', cell: 'F28' }, { level: 'Form4', cell: 'G28' }, { level: 'Form5', cell: 'H28' }, { level: 'LowerSixth', cell: 'I28' }, { level: 'UpperSixth', cell: 'J28' }], francophoneCells: [{ level: '6e', cell: 'M28' }, { level: '5e', cell: 'N28' }, { level: '4e', cell: 'O28' }, { level: '3e', cell: 'P28' }, { level: '2nde', cell: 'Q28' }, { level: '1ere', cell: 'R28' }, { level: 'Tle', cell: 'S28' }], otherCell: 'K28' },
  { fieldCode: '5113', discipline: 'Langue et Culture Nationale', anglophoneCells: [{ level: 'Form1', cell: 'D29' }, { level: 'Form2', cell: 'E29' }, { level: 'Form3', cell: 'F29' }, { level: 'Form4', cell: 'G29' }, { level: 'Form5', cell: 'H29' }, { level: 'LowerSixth', cell: 'I29' }, { level: 'UpperSixth', cell: 'J29' }], francophoneCells: [{ level: '6e', cell: 'M29' }, { level: '5e', cell: 'N29' }, { level: '4e', cell: 'O29' }, { level: '3e', cell: 'P29' }, { level: '2nde', cell: 'Q29' }, { level: '1ere', cell: 'R29' }, { level: 'Tle', cell: 'S29' }], otherCell: 'K29' },
  { fieldCode: '5114', discipline: 'Art', anglophoneCells: [{ level: 'Form1', cell: 'D30' }, { level: 'Form2', cell: 'E30' }, { level: 'Form3', cell: 'F30' }, { level: 'Form4', cell: 'G30' }, { level: 'Form5', cell: 'H30' }, { level: 'LowerSixth', cell: 'I30' }, { level: 'UpperSixth', cell: 'J30' }], francophoneCells: [{ level: '6e', cell: 'M30' }, { level: '5e', cell: 'N30' }, { level: '4e', cell: 'O30' }, { level: '3e', cell: 'P30' }, { level: '2nde', cell: 'Q30' }, { level: '1ere', cell: 'R30' }, { level: 'Tle', cell: 'S30' }], otherCell: 'K30' },
  { fieldCode: '5115', discipline: 'Economics', anglophoneCells: [{ level: 'Form1', cell: 'D31' }, { level: 'Form2', cell: 'E31' }, { level: 'Form3', cell: 'F31' }, { level: 'Form4', cell: 'G31' }, { level: 'Form5', cell: 'H31' }, { level: 'LowerSixth', cell: 'I31' }, { level: 'UpperSixth', cell: 'J31' }], francophoneCells: [{ level: '6e', cell: 'M31' }, { level: '5e', cell: 'N31' }, { level: '4e', cell: 'O31' }, { level: '3e', cell: 'P31' }, { level: '2nde', cell: 'Q31' }, { level: '1ere', cell: 'R31' }, { level: 'Tle', cell: 'S31' }], otherCell: 'K31' },
  { fieldCode: '5116', discipline: 'Commerce', anglophoneCells: [{ level: 'Form1', cell: 'D32' }, { level: 'Form2', cell: 'E32' }, { level: 'Form3', cell: 'F32' }, { level: 'Form4', cell: 'G32' }, { level: 'Form5', cell: 'H32' }, { level: 'LowerSixth', cell: 'I32' }, { level: 'UpperSixth', cell: 'J32' }], francophoneCells: [{ level: '6e', cell: 'M32' }, { level: '5e', cell: 'N32' }, { level: '4e', cell: 'O32' }, { level: '3e', cell: 'P32' }, { level: '2nde', cell: 'Q32' }, { level: '1ere', cell: 'R32' }, { level: 'Tle', cell: 'S32' }], otherCell: 'K32' },
  { fieldCode: '5117', discipline: 'Latin', anglophoneCells: [{ level: 'Form1', cell: 'D33' }, { level: 'Form2', cell: 'E33' }, { level: 'Form3', cell: 'F33' }, { level: 'Form4', cell: 'G33' }, { level: 'Form5', cell: 'H33' }, { level: 'LowerSixth', cell: 'I33' }, { level: 'UpperSixth', cell: 'J33' }], francophoneCells: [{ level: '6e', cell: 'M33' }, { level: '5e', cell: 'N33' }, { level: '4e', cell: 'O33' }, { level: '3e', cell: 'P33' }, { level: '2nde', cell: 'Q33' }, { level: '1ere', cell: 'R33' }, { level: 'Tle', cell: 'S33' }], otherCell: 'K33' },
  { fieldCode: '5118', discipline: 'English Literature', anglophoneCells: [{ level: 'Form1', cell: 'D34' }, { level: 'Form2', cell: 'E34' }, { level: 'Form3', cell: 'F34' }, { level: 'Form4', cell: 'G34' }, { level: 'Form5', cell: 'H34' }, { level: 'LowerSixth', cell: 'I34' }, { level: 'UpperSixth', cell: 'J34' }], francophoneCells: [{ level: '6e', cell: 'M34' }, { level: '5e', cell: 'N34' }, { level: '4e', cell: 'O34' }, { level: '3e', cell: 'P34' }, { level: '2nde', cell: 'Q34' }, { level: '1ere', cell: 'R34' }, { level: 'Tle', cell: 'S34' }], otherCell: 'K34' },
  { fieldCode: '5119', discipline: 'Religion/Religious', anglophoneCells: [{ level: 'Form1', cell: 'D35' }, { level: 'Form2', cell: 'E35' }, { level: 'Form3', cell: 'F35' }, { level: 'Form4', cell: 'G35' }, { level: 'Form5', cell: 'H35' }, { level: 'LowerSixth', cell: 'I35' }, { level: 'UpperSixth', cell: 'J35' }], francophoneCells: [{ level: '6e', cell: 'M35' }, { level: '5e', cell: 'N35' }, { level: '4e', cell: 'O35' }, { level: '3e', cell: 'P35' }, { level: '2nde', cell: 'Q35' }, { level: '1ere', cell: 'R35' }, { level: 'Tle', cell: 'S35' }], otherCell: 'K35' },
  { fieldCode: '5120', discipline: 'Electromecanique/Electromechanics', anglophoneCells: [{ level: 'Form1', cell: 'D36' }, { level: 'Form2', cell: 'E36' }, { level: 'Form3', cell: 'F36' }, { level: 'Form4', cell: 'G36' }, { level: 'Form5', cell: 'H36' }, { level: 'LowerSixth', cell: 'I36' }, { level: 'UpperSixth', cell: 'J36' }], francophoneCells: [{ level: '6e', cell: 'M36' }, { level: '5e', cell: 'N36' }, { level: '4e', cell: 'O36' }, { level: '3e', cell: 'P36' }, { level: '2nde', cell: 'Q36' }, { level: '1ere', cell: 'R36' }, { level: 'Tle', cell: 'S36' }], otherCell: 'K36' },
  { fieldCode: '5121', discipline: 'Mecanique auto/Motor Mechanics', anglophoneCells: [{ level: 'Form1', cell: 'D37' }, { level: 'Form2', cell: 'E37' }, { level: 'Form3', cell: 'F37' }, { level: 'Form4', cell: 'G37' }, { level: 'Form5', cell: 'H37' }, { level: 'LowerSixth', cell: 'I37' }, { level: 'UpperSixth', cell: 'J37' }], francophoneCells: [{ level: '6e', cell: 'M37' }, { level: '5e', cell: 'N37' }, { level: '4e', cell: 'O37' }, { level: '3e', cell: 'P37' }, { level: '2nde', cell: 'Q37' }, { level: '1ere', cell: 'R37' }, { level: 'Tle', cell: 'S37' }], otherCell: 'K37' },
  { fieldCode: '5122', discipline: 'Metiers du Bois/Wood Works', anglophoneCells: [{ level: 'Form1', cell: 'D38' }, { level: 'Form2', cell: 'E38' }, { level: 'Form3', cell: 'F38' }, { level: 'Form4', cell: 'G38' }, { level: 'Form5', cell: 'H38' }, { level: 'LowerSixth', cell: 'I38' }, { level: 'UpperSixth', cell: 'J38' }], francophoneCells: [{ level: '6e', cell: 'M38' }, { level: '5e', cell: 'N38' }, { level: '4e', cell: 'O38' }, { level: '3e', cell: 'P38' }, { level: '2nde', cell: 'Q38' }, { level: '1ere', cell: 'R38' }, { level: 'Tle', cell: 'S38' }], otherCell: 'K38' },
  { fieldCode: '5123', discipline: 'Genie civil/Civil Engineering', anglophoneCells: [{ level: 'Form1', cell: 'D39' }, { level: 'Form2', cell: 'E39' }, { level: 'Form3', cell: 'F39' }, { level: 'Form4', cell: 'G39' }, { level: 'Form5', cell: 'H39' }, { level: 'LowerSixth', cell: 'I39' }, { level: 'UpperSixth', cell: 'J39' }], francophoneCells: [{ level: '6e', cell: 'M39' }, { level: '5e', cell: 'N39' }, { level: '4e', cell: 'O39' }, { level: '3e', cell: 'P39' }, { level: '2nde', cell: 'Q39' }, { level: '1ere', cell: 'R39' }, { level: 'Tle', cell: 'S39' }], otherCell: 'K39' },
  { fieldCode: '5124', discipline: 'Fabrication Mecanique/Manuf Mechanics', anglophoneCells: [{ level: 'Form1', cell: 'D40' }, { level: 'Form2', cell: 'E40' }, { level: 'Form3', cell: 'F40' }, { level: 'Form4', cell: 'G40' }, { level: 'Form5', cell: 'H40' }, { level: 'LowerSixth', cell: 'I40' }, { level: 'UpperSixth', cell: 'J40' }], francophoneCells: [{ level: '6e', cell: 'M40' }, { level: '5e', cell: 'N40' }, { level: '4e', cell: 'O40' }, { level: '3e', cell: 'P40' }, { level: '2nde', cell: 'Q40' }, { level: '1ere', cell: 'R40' }, { level: 'Tle', cell: 'S40' }], otherCell: 'K40' },
  { fieldCode: '5125', discipline: 'Construction Mecanique/Mechanic construction', anglophoneCells: [{ level: 'Form1', cell: 'D41' }, { level: 'Form2', cell: 'E41' }, { level: 'Form3', cell: 'F41' }, { level: 'Form4', cell: 'G41' }, { level: 'Form5', cell: 'H41' }, { level: 'LowerSixth', cell: 'I41' }, { level: 'UpperSixth', cell: 'J41' }], francophoneCells: [{ level: '6e', cell: 'M41' }, { level: '5e', cell: 'N41' }, { level: '4e', cell: 'O41' }, { level: '3e', cell: 'P41' }, { level: '2nde', cell: 'Q41' }, { level: '1ere', cell: 'R41' }, { level: 'Tle', cell: 'S41' }], otherCell: 'K41' },
  { fieldCode: '5126', discipline: 'Action et Communication Administrative', anglophoneCells: [{ level: 'Form1', cell: 'D42' }, { level: 'Form2', cell: 'E42' }, { level: 'Form3', cell: 'F42' }, { level: 'Form4', cell: 'G42' }, { level: 'Form5', cell: 'H42' }, { level: 'LowerSixth', cell: 'I42' }, { level: 'UpperSixth', cell: 'J42' }], francophoneCells: [{ level: '6e', cell: 'M42' }, { level: '5e', cell: 'N42' }, { level: '4e', cell: 'O42' }, { level: '3e', cell: 'P42' }, { level: '2nde', cell: 'Q42' }, { level: '1ere', cell: 'R42' }, { level: 'Tle', cell: 'S42' }], otherCell: 'K42' },
  { fieldCode: '5127', discipline: 'Action et Communication Commerciale', anglophoneCells: [{ level: 'Form1', cell: 'D43' }, { level: 'Form2', cell: 'E43' }, { level: 'Form3', cell: 'F43' }, { level: 'Form4', cell: 'G43' }, { level: 'Form5', cell: 'H43' }, { level: 'LowerSixth', cell: 'I43' }, { level: 'UpperSixth', cell: 'J43' }], francophoneCells: [{ level: '6e', cell: 'M43' }, { level: '5e', cell: 'N43' }, { level: '4e', cell: 'O43' }, { level: '3e', cell: 'P43' }, { level: '2nde', cell: 'Q43' }, { level: '1ere', cell: 'R43' }, { level: 'Tle', cell: 'S43' }], otherCell: 'K43' },
  { fieldCode: '5128', discipline: 'Comptabilite et gestion/Accounting & management', anglophoneCells: [{ level: 'Form1', cell: 'D44' }, { level: 'Form2', cell: 'E44' }, { level: 'Form3', cell: 'F44' }, { level: 'Form4', cell: 'G44' }, { level: 'Form5', cell: 'H44' }, { level: 'LowerSixth', cell: 'I44' }, { level: 'UpperSixth', cell: 'J44' }], francophoneCells: [{ level: '6e', cell: 'M44' }, { level: '5e', cell: 'N44' }, { level: '4e', cell: 'O44' }, { level: '3e', cell: 'P44' }, { level: '2nde', cell: 'Q44' }, { level: '1ere', cell: 'R44' }, { level: 'Tle', cell: 'S44' }], otherCell: 'K44' },
  { fieldCode: '5129', discipline: 'Economie Social et Familiale/Home Economics', anglophoneCells: [{ level: 'Form1', cell: 'D45' }, { level: 'Form2', cell: 'E45' }, { level: 'Form3', cell: 'F45' }, { level: 'Form4', cell: 'G45' }, { level: 'Form5', cell: 'H45' }, { level: 'LowerSixth', cell: 'I45' }, { level: 'UpperSixth', cell: 'J45' }], francophoneCells: [{ level: '6e', cell: 'M45' }, { level: '5e', cell: 'N45' }, { level: '4e', cell: 'O45' }, { level: '3e', cell: 'P45' }, { level: '2nde', cell: 'Q45' }, { level: '1ere', cell: 'R45' }, { level: 'Tle', cell: 'S45' }], otherCell: 'K45' },
  { fieldCode: '5130', discipline: 'Industrie textile et de l"Habillement/Textile & clothing Industry', anglophoneCells: [{ level: 'Form1', cell: 'D46' }, { level: 'Form2', cell: 'E46' }, { level: 'Form3', cell: 'F46' }, { level: 'Form4', cell: 'G46' }, { level: 'Form5', cell: 'H46' }, { level: 'LowerSixth', cell: 'I46' }, { level: 'UpperSixth', cell: 'J46' }], francophoneCells: [{ level: '6e', cell: 'M46' }, { level: '5e', cell: 'N46' }, { level: '4e', cell: 'O46' }, { level: '3e', cell: 'P46' }, { level: '2nde', cell: 'Q46' }, { level: '1ere', cell: 'R46' }, { level: 'Tle', cell: 'S46' }], otherCell: 'K46' },
  { fieldCode: '5131', discipline: 'Legislation/Legislation', anglophoneCells: [{ level: 'Form1', cell: 'D47' }, { level: 'Form2', cell: 'E47' }, { level: 'Form3', cell: 'F47' }, { level: 'Form4', cell: 'G47' }, { level: 'Form5', cell: 'H47' }, { level: 'LowerSixth', cell: 'I47' }, { level: 'UpperSixth', cell: 'J47' }], francophoneCells: [{ level: '6e', cell: 'M47' }, { level: '5e', cell: 'N47' }, { level: '4e', cell: 'O47' }, { level: '3e', cell: 'P47' }, { level: '2nde', cell: 'Q47' }, { level: '1ere', cell: 'R47' }, { level: 'Tle', cell: 'S47' }], otherCell: 'K47' },
  { fieldCode: '5132', discipline: 'Autres/Other', anglophoneCells: [{ level: 'Form1', cell: 'D48' }, { level: 'Form2', cell: 'E48' }, { level: 'Form3', cell: 'F48' }, { level: 'Form4', cell: 'G48' }, { level: 'Form5', cell: 'H48' }, { level: 'LowerSixth', cell: 'I48' }, { level: 'UpperSixth', cell: 'J48' }], francophoneCells: [{ level: '6e', cell: 'M48' }, { level: '5e', cell: 'N48' }, { level: '4e', cell: 'O48' }, { level: '3e', cell: 'P48' }, { level: '2nde', cell: 'Q48' }, { level: '1ere', cell: 'R48' }, { level: 'Tle', cell: 'S48' }], otherCell: 'K48' },
];
